// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DirectionAction.proto
// Protobuf C++ Version: 5.27.3

#include "DirectionAction.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr DirectionAction::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        table_id_{::int64_t{0}},
        bet_amount_{::int64_t{0}},
        nt_type_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DirectionAction::DirectionAction(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct DirectionActionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DirectionActionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DirectionActionDefaultTypeInternal() {}
  union {
    DirectionAction _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DirectionActionDefaultTypeInternal _DirectionAction_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_DirectionAction_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_DirectionAction_2eproto = nullptr;
const ::uint32_t
    TableStruct_DirectionAction_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::DirectionAction, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::DirectionAction, _impl_.nt_type_),
        PROTOBUF_FIELD_OFFSET(::DirectionAction, _impl_.token_),
        PROTOBUF_FIELD_OFFSET(::DirectionAction, _impl_.table_id_),
        PROTOBUF_FIELD_OFFSET(::DirectionAction, _impl_.bet_amount_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::DirectionAction)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_DirectionAction_default_instance_._instance,
};
const char descriptor_table_protodef_DirectionAction_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\025DirectionAction.proto\"W\n\017DirectionActi"
    "on\022\017\n\007nt_type\030\001 \001(\005\022\r\n\005token\030\002 \001(\t\022\020\n\010ta"
    "ble_id\030\003 \001(\003\022\022\n\nbet_amount\030\004 \001(\003b\006proto3"
};
static ::absl::once_flag descriptor_table_DirectionAction_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_DirectionAction_2eproto = {
    false,
    false,
    120,
    descriptor_table_protodef_DirectionAction_2eproto,
    "DirectionAction.proto",
    &descriptor_table_DirectionAction_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_DirectionAction_2eproto::offsets,
    file_level_enum_descriptors_DirectionAction_2eproto,
    file_level_service_descriptors_DirectionAction_2eproto,
};
// ===================================================================

class DirectionAction::_Internal {
 public:
};

DirectionAction::DirectionAction(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:DirectionAction)
}
inline PROTOBUF_NDEBUG_INLINE DirectionAction::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::DirectionAction& from_msg)
      : token_(arena, from.token_),
        _cached_size_{0} {}

DirectionAction::DirectionAction(
    ::google::protobuf::Arena* arena,
    const DirectionAction& from)
    : ::google::protobuf::Message(arena) {
  DirectionAction* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, table_id_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, table_id_),
           offsetof(Impl_, nt_type_) -
               offsetof(Impl_, table_id_) +
               sizeof(Impl_::nt_type_));

  // @@protoc_insertion_point(copy_constructor:DirectionAction)
}
inline PROTOBUF_NDEBUG_INLINE DirectionAction::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : token_(arena),
        _cached_size_{0} {}

inline void DirectionAction::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, table_id_),
           0,
           offsetof(Impl_, nt_type_) -
               offsetof(Impl_, table_id_) +
               sizeof(Impl_::nt_type_));
}
DirectionAction::~DirectionAction() {
  // @@protoc_insertion_point(destructor:DirectionAction)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void DirectionAction::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.token_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
DirectionAction::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(DirectionAction, _impl_._cached_size_),
              false,
          },
          &DirectionAction::MergeImpl,
          &DirectionAction::kDescriptorMethods,
          &descriptor_table_DirectionAction_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 29, 2> DirectionAction::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_DirectionAction_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::DirectionAction>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 bet_amount = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(DirectionAction, _impl_.bet_amount_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(DirectionAction, _impl_.bet_amount_)}},
    // int32 nt_type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DirectionAction, _impl_.nt_type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(DirectionAction, _impl_.nt_type_)}},
    // string token = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(DirectionAction, _impl_.token_)}},
    // int64 table_id = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(DirectionAction, _impl_.table_id_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(DirectionAction, _impl_.table_id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 nt_type = 1;
    {PROTOBUF_FIELD_OFFSET(DirectionAction, _impl_.nt_type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string token = 2;
    {PROTOBUF_FIELD_OFFSET(DirectionAction, _impl_.token_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int64 table_id = 3;
    {PROTOBUF_FIELD_OFFSET(DirectionAction, _impl_.table_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // int64 bet_amount = 4;
    {PROTOBUF_FIELD_OFFSET(DirectionAction, _impl_.bet_amount_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\17\0\5\0\0\0\0\0"
    "DirectionAction"
    "token"
  }},
};

PROTOBUF_NOINLINE void DirectionAction::Clear() {
// @@protoc_insertion_point(message_clear_start:DirectionAction)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.token_.ClearToEmpty();
  ::memset(&_impl_.table_id_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.nt_type_) -
      reinterpret_cast<char*>(&_impl_.table_id_)) + sizeof(_impl_.nt_type_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* DirectionAction::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DirectionAction)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 nt_type = 1;
  if (this->_internal_nt_type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_nt_type(), target);
  }

  // string token = 2;
  if (!this->_internal_token().empty()) {
    const std::string& _s = this->_internal_token();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "DirectionAction.token");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // int64 table_id = 3;
  if (this->_internal_table_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<3>(
            stream, this->_internal_table_id(), target);
  }

  // int64 bet_amount = 4;
  if (this->_internal_bet_amount() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<4>(
            stream, this->_internal_bet_amount(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DirectionAction)
  return target;
}

::size_t DirectionAction::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DirectionAction)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // string token = 2;
  if (!this->_internal_token().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_token());
  }

  // int64 table_id = 3;
  if (this->_internal_table_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_table_id());
  }

  // int64 bet_amount = 4;
  if (this->_internal_bet_amount() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_bet_amount());
  }

  // int32 nt_type = 1;
  if (this->_internal_nt_type() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_nt_type());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void DirectionAction::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DirectionAction*>(&to_msg);
  auto& from = static_cast<const DirectionAction&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DirectionAction)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_token().empty()) {
    _this->_internal_set_token(from._internal_token());
  }
  if (from._internal_table_id() != 0) {
    _this->_impl_.table_id_ = from._impl_.table_id_;
  }
  if (from._internal_bet_amount() != 0) {
    _this->_impl_.bet_amount_ = from._impl_.bet_amount_;
  }
  if (from._internal_nt_type() != 0) {
    _this->_impl_.nt_type_ = from._impl_.nt_type_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DirectionAction::CopyFrom(const DirectionAction& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DirectionAction)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DirectionAction::InternalSwap(DirectionAction* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.token_, &other->_impl_.token_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DirectionAction, _impl_.nt_type_)
      + sizeof(DirectionAction::_impl_.nt_type_)
      - PROTOBUF_FIELD_OFFSET(DirectionAction, _impl_.table_id_)>(
          reinterpret_cast<char*>(&_impl_.table_id_),
          reinterpret_cast<char*>(&other->_impl_.table_id_));
}

::google::protobuf::Metadata DirectionAction::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_DirectionAction_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
