// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: DirectionAction.proto
// Protobuf C++ Version: 5.27.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_DirectionAction_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_DirectionAction_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_DirectionAction_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_DirectionAction_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_DirectionAction_2eproto;
class DirectionAction;
struct DirectionActionDefaultTypeInternal;
extern DirectionActionDefaultTypeInternal _DirectionAction_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class DirectionAction final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:DirectionAction) */ {
 public:
  inline DirectionAction() : DirectionAction(nullptr) {}
  ~DirectionAction() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR DirectionAction(
      ::google::protobuf::internal::ConstantInitialized);

  inline DirectionAction(const DirectionAction& from) : DirectionAction(nullptr, from) {}
  inline DirectionAction(DirectionAction&& from) noexcept
      : DirectionAction(nullptr, std::move(from)) {}
  inline DirectionAction& operator=(const DirectionAction& from) {
    CopyFrom(from);
    return *this;
  }
  inline DirectionAction& operator=(DirectionAction&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const DirectionAction& default_instance() {
    return *internal_default_instance();
  }
  static inline const DirectionAction* internal_default_instance() {
    return reinterpret_cast<const DirectionAction*>(
        &_DirectionAction_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(DirectionAction& a, DirectionAction& b) { a.Swap(&b); }
  inline void Swap(DirectionAction* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DirectionAction* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DirectionAction* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<DirectionAction>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const DirectionAction& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const DirectionAction& from) { DirectionAction::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(DirectionAction* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "DirectionAction"; }

 protected:
  explicit DirectionAction(::google::protobuf::Arena* arena);
  DirectionAction(::google::protobuf::Arena* arena, const DirectionAction& from);
  DirectionAction(::google::protobuf::Arena* arena, DirectionAction&& from) noexcept
      : DirectionAction(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTokenFieldNumber = 2,
    kTableIdFieldNumber = 3,
    kBetAmountFieldNumber = 4,
    kNtTypeFieldNumber = 1,
  };
  // string token = 2;
  void clear_token() ;
  const std::string& token() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_token(Arg_&& arg, Args_... args);
  std::string* mutable_token();
  PROTOBUF_NODISCARD std::string* release_token();
  void set_allocated_token(std::string* value);

  private:
  const std::string& _internal_token() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_token(
      const std::string& value);
  std::string* _internal_mutable_token();

  public:
  // int64 table_id = 3;
  void clear_table_id() ;
  ::int64_t table_id() const;
  void set_table_id(::int64_t value);

  private:
  ::int64_t _internal_table_id() const;
  void _internal_set_table_id(::int64_t value);

  public:
  // int64 bet_amount = 4;
  void clear_bet_amount() ;
  ::int64_t bet_amount() const;
  void set_bet_amount(::int64_t value);

  private:
  ::int64_t _internal_bet_amount() const;
  void _internal_set_bet_amount(::int64_t value);

  public:
  // int32 nt_type = 1;
  void clear_nt_type() ;
  ::int32_t nt_type() const;
  void set_nt_type(::int32_t value);

  private:
  ::int32_t _internal_nt_type() const;
  void _internal_set_nt_type(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:DirectionAction)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      29, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_DirectionAction_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const DirectionAction& from_msg);
    ::google::protobuf::internal::ArenaStringPtr token_;
    ::int64_t table_id_;
    ::int64_t bet_amount_;
    ::int32_t nt_type_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_DirectionAction_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// DirectionAction

// int32 nt_type = 1;
inline void DirectionAction::clear_nt_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nt_type_ = 0;
}
inline ::int32_t DirectionAction::nt_type() const {
  // @@protoc_insertion_point(field_get:DirectionAction.nt_type)
  return _internal_nt_type();
}
inline void DirectionAction::set_nt_type(::int32_t value) {
  _internal_set_nt_type(value);
  // @@protoc_insertion_point(field_set:DirectionAction.nt_type)
}
inline ::int32_t DirectionAction::_internal_nt_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nt_type_;
}
inline void DirectionAction::_internal_set_nt_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nt_type_ = value;
}

// string token = 2;
inline void DirectionAction::clear_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.token_.ClearToEmpty();
}
inline const std::string& DirectionAction::token() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:DirectionAction.token)
  return _internal_token();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void DirectionAction::set_token(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.token_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:DirectionAction.token)
}
inline std::string* DirectionAction::mutable_token() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_token();
  // @@protoc_insertion_point(field_mutable:DirectionAction.token)
  return _s;
}
inline const std::string& DirectionAction::_internal_token() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.token_.Get();
}
inline void DirectionAction::_internal_set_token(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.token_.Set(value, GetArena());
}
inline std::string* DirectionAction::_internal_mutable_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.token_.Mutable( GetArena());
}
inline std::string* DirectionAction::release_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:DirectionAction.token)
  return _impl_.token_.Release();
}
inline void DirectionAction::set_allocated_token(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.token_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.token_.IsDefault()) {
          _impl_.token_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DirectionAction.token)
}

// int64 table_id = 3;
inline void DirectionAction::clear_table_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.table_id_ = ::int64_t{0};
}
inline ::int64_t DirectionAction::table_id() const {
  // @@protoc_insertion_point(field_get:DirectionAction.table_id)
  return _internal_table_id();
}
inline void DirectionAction::set_table_id(::int64_t value) {
  _internal_set_table_id(value);
  // @@protoc_insertion_point(field_set:DirectionAction.table_id)
}
inline ::int64_t DirectionAction::_internal_table_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.table_id_;
}
inline void DirectionAction::_internal_set_table_id(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.table_id_ = value;
}

// int64 bet_amount = 4;
inline void DirectionAction::clear_bet_amount() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bet_amount_ = ::int64_t{0};
}
inline ::int64_t DirectionAction::bet_amount() const {
  // @@protoc_insertion_point(field_get:DirectionAction.bet_amount)
  return _internal_bet_amount();
}
inline void DirectionAction::set_bet_amount(::int64_t value) {
  _internal_set_bet_amount(value);
  // @@protoc_insertion_point(field_set:DirectionAction.bet_amount)
}
inline ::int64_t DirectionAction::_internal_bet_amount() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bet_amount_;
}
inline void DirectionAction::_internal_set_bet_amount(::int64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bet_amount_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_DirectionAction_2eproto_2epb_2eh
